E4.1:
select avg(HOUR_RATE) from HOURS;
E4.2:
select avg(ATTRACT_AGE) from ATTRACTION where PARK_CODE = 'UK3452';
E4.3:
select distinct(EMP_NUM), sum(HOURS_PER_ATTRACT) from HOURS group by EMP_NUM, HOURS_PER_ATTRACT;
E4.4:
select ATTRACT_NO, min(HOUR_RATE),max(HOUR_RATE) from HOURS group by ATTRACT_NO;
E4.5:
 select EMP_NUM, ATTRACT_NO, avg(HOURS_PER_ATTRACT) from HOURS group by EMP_NUM having avg(HOURS_PER_ATTRACT)>=5;

E4.6:
select * from EMPLOYEE cross join HOURS;
-- to know how many rows were selected we will use count
select count(*) from EMPLOYEE cross join HOURS;
--THere were 77 rows selected

E4.7:
select EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, ATTRACT_NO,DATE_WORKED from EMPLOYEE join HOURS on EMPLOYEE.EMP_NUM = HOURS.EMP_NUM;

E4.8:
select EMPLOYEE.EMP_FNAME, EMPLOYEE.EMP_LNAME, HOURS.ATTRACT_NO,HOURS.DATE_WORKED, ATTRACTION.ATTRACT_NO from EMPLOYEE join HOURS on EMPLOYEE.EMP_NUM = HOURS.EMP_NUM join ATTRACTION on ATTRACTION.ATTRACT_NO = HOURS.ATTRACT_NO ;

E4.9:
select PARK_NAME, sum(TICKET_PRICE) from THEMEPARK,TICKET where PARK_COUNTRY in ('UK','FR') group by PARK_NAME;

E4.10:
select SALES.SALE_DATE, SALES_LINE.LINE_QTY, LINE_PRICE from SALES_LINE join SALES on SALES_LINE.TRANSACTION_NO = SALES.TRANSACTION_NO having SALE_DATE = '2007-05-18';


